#!/bin/bash

# Define the test function
run_test()
{
    echo "Running test: $1"
    valgrind --suppressions=../readline.supp --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --log-file=valgrind-out.txt .././minishell -c "$1"
    echo
}

# Run the tests
run_test "echo $?"
run_test "echo '$ '"
run_test "echo $USER"
run_test "echo $NONEXIST"
run_test "echo $USER$PATH$PWD"
run_test "echo \"$USER$PATH$PWD\""
run_test "echo '$USER$PATH$PWD'"
run_test "echo '$USER\",\"\$PATH,\$PWD'"
run_test "$NONEXIST"
run_test "$NONEXIST $NONEXIST"
run_test "VAR: export TMPENVVAR"
run_test "VAR: export TMPENVVAR=echo"
run_test "VAR: export TMPENVVAR=\"-n\""
run_test "echo '|$USER|'"
run_test "echo '|$USE|'"
run_test "echo '|$USER_|'"
run_test "'echo' hi"
run_test "'''echo' hi"
run_test "'echo' 'hi'"
run_test "'echo' 'hi'''"
run_test "\"echo\" hi"
run_test "\"\"\"echo\" hi"
run_test "\"echo\" \"hi\""
run_test "\"echo\" \"hi\"\"\""
run_test "echo '\"\"\"\"\"\"\"\"\"\"\"\"'"
run_test "echo '\"$\"'"
run_test "echo \"|$USER|\""
run_test "echo \"|$USE|\""
run_test "\" echo\""
run_test "' echo'"
run_test "\"\"echo"
run_test "\" \"echo"
run_test "''echo"
run_test "' 'echo"
run_test "''''''''''echo hi"
run_test "\"\"\"\"\"\"\"\"\"\"echo hi"
run_test "EcHo hi"
run_test "ECHO hi"
run_test "\"ECHO\" hi"
run_test "'ECHO' hi"
run_test "echo    t  hi   t"
run_test "echo \"   t  hi   t    \""
run_test "echo '   t  hi   t    '"
run_test "echo $\"   t  hi   t    \""
run_test "echo $'   t  hi   t    '"
run_test "echo $'   r  hi   t    '"
run_test "echo hi~"
run_test "echo ~$USER"
run_test "echo ~false"
run_test "echo ~$USER/sdfsfsfsfdsfs"
run_test "test"
run_test "|test"
run_test "||test"
run_test "|< | test"
run_test "|<< | test"
run_test "|> | test"
run_test "|>> | test"
run_test "|| < test"
run_test "|| << test"
run_test "|| > test"
run_test "|| >> test"
run_test "|| test"
run_test "test | >"
run_test "test | >>"
run_test "test | <"
run_test "echo hiecho hi"
run_test "echo hi|echo hi"
run_test "echo hi |echo hi"
run_test "echo hi| echo hi"
run_test "echo hi | | echo hi"
run_test "echo hi ||| echo hi"
run_test "echo >"
run_test "echo >>"
run_test "echo <"
run_test "echo hi >< file"

# Print the valgrind output
cat valgrind-out.txt
rm valgrind-out.txt